spring.application.name=biblioteca

# =====================================
# Configuração do Banco de Dados MySQL
# =====================================
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=

# Dialeto e driver do MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Criação/atualização automática de tabelas
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (debug)
spring.jpa.show-sql=true

# Porta padrão do servidor
server.port=8080
